[program:clientthing]
command=/bin/sh /usr/share/clientthing/run-input-bridge.sh
user=root
numprocs=1
autostart=true
autorestart=true
startsecs=0
priority=85
redirect_stderr=false
stdout_logfile=/var/log/clientthing.info
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=3
stdout_capture_maxbytes=1MB
stdout_events_enabled=false
stderr_logfile=/var/log/clientthing.err
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=3
stderr_capture_maxbytes=1MB
stderr_events_enabled=false
environment=HOME="/root",XDG_CACHE_HOME="/var/cache",BRIDGE_SERVER_URL="http://127.0.0.1:3000",BRIDGE_DEVICE_ID="input-bridge"
