services:
  arm-sidecar:
    extends:
      file: ./compose.base.yaml
      service: arm-sidecar
    container_name: arm-sidecar
    pull_policy: always
    environment:
      ARM_SIDECAR_MODE: live
      ARM_SETTINGS_PATH: /arm/settings/settings.conf
      ARM_LOGS_DIR: /arm/logs
      ARM_PROGRESS_LOGS_DIR: /arm/logs/progress
      ARM_ARM_LOG_PATH: /arm/logs/arm.log
      ARM_TRANSCODE_LOG_PATH: /arm/logs/transcode.log
    volumes:
      - arm_sidecar_data:/app/data
      - ${ARM_HOST_SETTINGS_PATH}:/arm/settings/settings.conf:rw
      - ${ARM_HOST_LOGS_PATH}:/arm/logs:ro

  serverthing:
    extends:
      file: ./compose.base.yaml
      service: serverthing
    container_name: serverthing
    pull_policy: always
    volumes:
      - serverthing_data:/app/data

volumes:
  arm_sidecar_data:
  serverthing_data:
